config/routes.rb
Rails.application.routes.draw do
  devise_for :users
	resources :resumes, only: [:index, :new, :create, :destroy]
  root "resumes#index"
  # get 'resumes/index'
  # get 'resumes/new'
  # get 'resumes/create'
  # get 'resumes/destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/resume.rb
class Resume < ActiveRecord::Base
  mount_uploader :attachment, AttachmentUploader # Tells rails to use this uploader for this model.
  mount_uploader  :attachment1, AttachmentUploader
  mount_uploader  :attachment2, AttachmentUploader
  mount_uploader  :attachment3, AttachmentUploader
  validates :name, presence: true # Make sure the owner's name is present.
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

# after :registerable, entry
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :authenticate_user!


end

app/controllers/resumes_controller.rb
class ResumesController < ApplicationController
  def index
    @resumes = Resume.all.uniq
  end

  def new
    @resume = Resume.new
  end

  def create
    # byebug

    # Resume.create(name: params.require(:resume)[:name], attachment: params.require(:resume).permit(:attachment))

    Resume.create(name: params.require(:resume)[:name], attachment:  params.require(:resume)[:attachment])
    Resume.create(name: params.require(:resume)[:name], attachment:  params.require(:resume)[:attachment1])
    Resume.create(name: params.require(:resume)[:name], attachment:  params.require(:resume)[:attachment2])
    Resume.create(name: params.require(:resume)[:name], attachment:  params.require(:resume)[:attachment3])


    # @resume = Resume.new(params.require(:resume).permit(:name, :attachment))
    # @resume.save
    # @resume = Resume.new(params.require(:resume).permit(:name, :attachment1))
    # @resume.save
    # @resume = Resume.new(params.require(:resume).permit(:name, :attachment2))
    # @resume.save
    # @resume = Resume.new(params.require(:resume).permit(:name, :attachment3))


    # # byebug
    # if @resume.save
    redirect_to resumes_path#, notice: "The resume #{@resume.name} has been uploaded."
    # else
    #   render "new"
    # end
  end

  def destroy
    @resume = Resume.find(params[:id])
    @resume.destroy
    redirect_to resumes_path, notice:  "The PDF #{@resume.name} has been deleted."
  end

private
  def resume_params
    params.require(:resume).permit(:name, :attachment, :attachment1, :attachment2, :attachment3)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "PDF Uploader" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
    <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.2/html5shiv.min.js" type="text/javascript"></script>
    <![endif]-->
  </head>
  <body>

    <div class="navbar navbar-default navbar-static-top">
      <div class="container">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to 'PDF Uploader', root_path , class: "navbar-brand"%>
        <div class="navbar-collapse collapse navbar-responsive-collapse">
          <ul class="nav navbar-nav">
          </ul>

          <ul class="nav navbar-right col-md-4">
            <% if current_user %>
              <li class="col-md-8 user-name">
                <%= link_to ('<i class="fa fa-user"></i> ' + truncate(current_user.email, length: 25)).html_safe, edit_user_registration_path, title: 'Edit Profile' %>
              </li>
              <li class="col-md-1"> </li>
              <li class="col-md-3 logout"><%= link_to('Logout', destroy_user_session_path, class: 'btn btn-xs btn-danger', title: 'Logout', :method => :delete) %></li>
            <% else %>
              <li class="col-md-4 pull-right">
                <%= link_to('Sign In', new_user_session_path, class: 'btn btn-primary', title: 'Sign In') %>
              </li>
            <% end %>
          </ul>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
        

      

    </div> <!-- /container -->

  </body>
</html>

app/views/resumes/create.html.erb
<h1>Resumes#create</h1>
<p>Find me in app/views/resumes/create.html.erb</p>

app/views/resumes/destroy.html.erb
<h1>Resumes#destroy</h1>
<p>Find me in app/views/resumes/destroy.html.erb</p>

app/views/resumes/index.html.erb
<% if !flash[:notice].blank? %>
  <div class="alert alert-info">
  <%= flash[:notice] %>
  </div>
<% end %>
<br />
<%= link_to "Upload PDF", new_resume_path, class: "btn btn-primary" %>
<br />
<br />
<table class="table table-bordered table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Download Link</th>
      <th>&nbsp;</th>
    </tr>
  </thead>
  <tbody>
    <% @resumes.each do |resume| %>
      <tr>
        <td><%= resume.name %></td>
        <td><%= link_to resume.attachment.to_s.gsub('/', ' ').split.last, resume.attachment_url %></td>
        <td><%= button_to "Delete",  resume, method: :delete, class: "btn btn-danger", confirm: "Are you sure that you wish to delete #{resume.name}?" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/resumes/new.html.erb
<% if !@resume.errors.empty? %>
  <div class="alert alert-error">
    <ul>
      <% @resume.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<div class="well">
  <%= form_for @resume, :html => {multipart: true, :class => "form-horizontal image" }  do |f| %>
    <div class="form-group">
      <%= f.label :name, :class => 'control-label col-lg-2'%>
      <%= f.text_field :name, :class => 'form-control' %>
    </div>
    <br><br>
    <%= f.label :Resume %>
    <%= f.file_field :attachment %>
    <br><br>
    <%= f.label :LOR %>
    <%= f.file_field :attachment1 %>
    <br><br>
    <%= f.label :Gradesheet %>
    <%= f.file_field :attachment2 %>
    <br><br>
    <%= f.label :Recommendation %>
    <%= f.file_field :attachment3 %>
    <br><br>
      
    <%= f.submit "Save", class: "btn btn-primary" %>
  <% end %>
</div>